import { MapGeoJSONFeature } from 'maplibre-gl'
import { BUILDING_ATTRIBUTE_KEYS, GEOGRAPHY_ATTRIBUTE_KEYS } from '@/lib/config'

export type Coordinates = {
  lat: number
  lng: number
}

export type BoundingBox = {
  west: number
  south: number
  east: number
  north: number
}

export type Address = {
  label: string
  countryCode?: string
  countryName?: string
  stateCode?: string
  state?: string
  county?: string
  city?: string
  district?: string
  street?: string
  postalCode?: string
  houseNumber?: string
}

export type Location = {
  title: string
  id: string
  address: Address
  position: Coordinates
  access?: Coordinates[]
  mapView?: BoundingBox
}

export type ScenarioKey = 'current' | 'future'

export type GeographyKey =
  | 'county'
  | 'censusTract'
  | 'censusBlock'
  | 'state'
  | 'nation'

export type BuildingProperties = {
  [BUILDING_ATTRIBUTE_KEYS.rps_2011]: number
  [BUILDING_ATTRIBUTE_KEYS.rps_2047]: number
  [BUILDING_ATTRIBUTE_KEYS.bp_2011]: number
  [BUILDING_ATTRIBUTE_KEYS.bp_2047]: number
  [BUILDING_ATTRIBUTE_KEYS.crps_scott]: number
  [BUILDING_ATTRIBUTE_KEYS.bp_2011_riley]: number
  [BUILDING_ATTRIBUTE_KEYS.bp_2047_riley]: number
}

export type Building = Omit<MapGeoJSONFeature, 'properties'> & {
  id: string // id generated by tippecanoe, not durable across data versions
  properties: BuildingProperties
}

export type Geography = {
  [GEOGRAPHY_ATTRIBUTE_KEYS.building_count]: number
  [GEOGRAPHY_ATTRIBUTE_KEYS.mean_rps_2011]: number
  [GEOGRAPHY_ATTRIBUTE_KEYS.mean_rps_2047]: number
  [GEOGRAPHY_ATTRIBUTE_KEYS.rps_2011_median]: number
  [GEOGRAPHY_ATTRIBUTE_KEYS.rps_2047_median]: number
  [GEOGRAPHY_ATTRIBUTE_KEYS.risk_score_2011_hist]: string // stringified number[]
  [GEOGRAPHY_ATTRIBUTE_KEYS.risk_score_2047_hist]: string // stringified number[]
  [GEOGRAPHY_ATTRIBUTE_KEYS.geoid]: string
  [GEOGRAPHY_ATTRIBUTE_KEYS.bbox]: string
  [GEOGRAPHY_ATTRIBUTE_KEYS.name]?: string
}

export type Suggestion = {
  title: string
  id: string
  address: Address
}

// Attributes carried through the MTBS burned-area-boundaries vector tiles.
export type FireProperties = {
  event_id: string
  incid_name: string
  incid_type: string
  asmnt_type: string
  burnbndac: number
  ig_date: string
  year: number
}
